services:  
  mysqldb:
    image: mysql:8.0.29
    container_name: mysql
    ports:
      - '3306:3306'
    restart: 'no'
    environment:
      MYSQL_DATABASE: sampledb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password      
      MYSQL_ROOT_PASSWORD: JECCHuPWg6eRQVBr
    networks:
      - mydbnet
  phpmyadmin:
    depends_on:
      - mysqldb
    image: phpmyadmin/phpmyadmin
    restart: 'no'
    ports:
    - '8086:80'
    environment:
      PMA_HOST: 'mysqldb'
      PMA_USER: 'root'
      PMA_PASSWORD: 'JECCHuPWg6eRQVBr'
      MYSQL_ROOT_PASSWORD: 'JECCHuPWg6eRQVBr'
    networks:
      - mydbnet
networks:
  mydbnet: